# Generated by Django 5.1.15 on 2026-07-08 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'C-dur', 'A-mol'.", max_length=64, unique=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Major", "Major"),
                            ("Minor", "Natural minor"),
                            ("HarmonicMinor", "Harmonic minor"),
                            ("MelodicMinor", "Melodic minor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("root_pitch_class", models.SmallIntegerField(help_text="0-11, C=0.")),
                ("root_octave", models.PositiveSmallIntegerField(default=1)),
                (
                    "key_signature",
                    models.JSONField(
                        default=list,
                        help_text="Normalized incdec list: [{'name':'f2#','letter':'f','offset':1}, ...].",
                    ),
                ),
                (
                    "tonic_offset_override_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional override for the A/D/G tonic-offset anomaly.",
                        null=True,
                    ),
                ),
                (
                    "default_rhythm",
                    models.CharField(default="FreeStyle", max_length=32),
                ),
                ("draw_only_note_heads", models.BooleanField(default=True)),
                ("tempo", models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula_name",
                    models.CharField(
                        help_text="Formula family: 'Octave', 'Quinta', 'Extended', etc.",
                        max_length=255,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        default="",
                        help_text="Sub-variant: 'SKALA', 'ABC', 'KROM', '' (plain), ...",
                        max_length=255,
                    ),
                ),
                ("source_file", models.CharField(default="", max_length=512)),
                ("tempo", models.PositiveIntegerField(default=86)),
                ("draw_only_note_heads", models.BooleanField(default=False)),
                (
                    "default_rhythm",
                    models.CharField(default="FreeStyle", max_length=32),
                ),
                ("mid_bar_time", models.FloatField(default=0.1)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "key_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="relative.keymodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("key_model", "formula_name", "variant")},
            },
        ),
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bar_index", models.PositiveSmallIntegerField()),
                (
                    "degree",
                    models.CharField(
                        help_text="Scale-degree label, e.g. '1', '5\\'', '5,'.",
                        max_length=16,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("natural", "Natural"),
                            ("raised", "Raised"),
                            ("lowered", "Lowered"),
                        ],
                        default="natural",
                        max_length=16,
                    ),
                ),
                ("music_clef", models.CharField(default="Violin", max_length=32)),
                ("music_rhythm", models.CharField(default="FreeStyle", max_length=32)),
                ("music_mode_chord", models.CharField(default="", max_length=64)),
                ("is_incomplete_bar", models.BooleanField(default=False)),
                (
                    "incomplete_bar_playback_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="relative.exercise",
                    ),
                ),
                (
                    "key_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="relative.keymodel",
                    ),
                ),
            ],
            options={
                "ordering": ("bar_index",),
            },
        ),
        migrations.CreateModel(
            name="MusicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_index", models.PositiveSmallIntegerField()),
                ("horizontal_offset_ms", models.IntegerField(default=0)),
                ("duration", models.FloatField(default=0.125)),
                ("attack_decay_time", models.FloatField(blank=True, null=True)),
                ("volume", models.PositiveSmallIntegerField(default=80)),
                (
                    "note_name",
                    models.CharField(
                        help_text="Raw token, e.g. 'c1', 'f2#', 'e1r'.", max_length=16
                    ),
                ),
                (
                    "alias_degree",
                    models.CharField(
                        default="",
                        help_text="The scale-degree label from the source alias.",
                        max_length=16,
                    ),
                ),
                ("is_rest", models.BooleanField(default=False)),
                (
                    "is_enharmonic",
                    models.BooleanField(
                        default=False,
                        help_text="True = note inherits alteration from the key signature.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(default="MusicNoteBundle", max_length=64),
                ),
                ("pitch_class", models.SmallIntegerField(default=-1)),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="relative.bar",
                    ),
                ),
            ],
            options={
                "ordering": ("event_index",),
            },
        ),
        migrations.CreateModel(
            name="ScaleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Major", "Major"),
                            ("Minor", "Natural minor"),
                            ("HarmonicMinor", "Harmonic minor"),
                            ("MelodicMinor", "Melodic minor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("clef", models.CharField(default="Violin", max_length=32)),
                (
                    "default_rhythm",
                    models.CharField(default="FreeStyle", max_length=32),
                ),
                ("draw_only_note_heads", models.BooleanField(default=True)),
                (
                    "reference_key",
                    models.CharField(
                        help_text="The key used to define this template, e.g. 'C_Major'.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "unique_together": {("mode", "reference_key")},
            },
        ),
        migrations.AddField(
            model_name="keymodel",
            name="scale_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keys",
                to="relative.scalemodel",
            ),
        ),
        migrations.CreateModel(
            name="ScaleModelPitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.PositiveSmallIntegerField()),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("natural", "Natural"),
                            ("raised", "Raised"),
                            ("lowered", "Lowered"),
                        ],
                        default="natural",
                        max_length=16,
                    ),
                ),
                ("interval_semitones", models.SmallIntegerField()),
                ("reference_note_name", models.CharField(max_length=16)),
                (
                    "scale_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="relative.scalemodel",
                    ),
                ),
            ],
            options={
                "ordering": ("degree", "quality"),
                "unique_together": {("scale_model", "degree", "quality")},
            },
        ),
        migrations.CreateModel(
            name="ScaleModelTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.PositiveSmallIntegerField()),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("natural", "Natural"),
                            ("raised", "Raised"),
                            ("lowered", "Lowered"),
                        ],
                        default="natural",
                        max_length=16,
                    ),
                ),
                ("sequence_index", models.PositiveSmallIntegerField()),
                ("offset_ms", models.IntegerField(default=0)),
                ("duration", models.FloatField(default=0.125)),
                (
                    "scale_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timings",
                        to="relative.scalemodel",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence_index",),
                "unique_together": {("scale_model", "sequence_index", "quality")},
            },
        ),
    ]
