# Generated by Django 5.1.15 on 2026-07-14 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relative", "0002_rename_exercise_to_lesson"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bar",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Harmonic-function label from the source (e.g. Roman numeral 'I', 'IV').",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Formula", "Tonal-trichord formula"),
                    ("ChordsThirds", "Triads"),
                    ("ChordsSevenths", "Seventh chords"),
                    ("Intervals", "Intervals"),
                ],
                default="",
                help_text="Poly lesson category. Empty for mono.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="interval_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Poly interval family: 'Thirds', 'Fourths', 'Fifths', 'Sixths', 'Sevenths'.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="inversion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Figured-bass digits for poly chords: 53/63/64 (triads), 7/65/43/2 (sevenths).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="part",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Poly progressive section: '1', '2', '1-2', '3', '1-3'. Empty for mono.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="texture",
            field=models.CharField(
                choices=[
                    ("mono", "Monophonic (melodic)"),
                    ("poly", "Polyphonic (harmonic)"),
                ],
                default="mono",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="formula_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mono formula family: 'Octave', 'Quinta', 'Extended'. Empty for poly.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="key_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="relative.keymodel",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="variant",
            field=models.CharField(
                default="",
                help_text="Mono: 'SKALA', 'ABC', 'KROM', '' (plain), ... Poly: 'v<N>_<F|ABC>[+T]' — v1 = guided model (chord walk-up / interval with tonic), v2 = plain tones, v3 = letter names.",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={
                (
                    "key_model",
                    "texture",
                    "formula_name",
                    "category",
                    "inversion",
                    "interval_name",
                    "part",
                    "variant",
                )
            },
        ),
    ]
