# Generated by Django 5.1.15 on 2026-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relative", "0003_alter_lesson_unique_together_bar_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Formula", "Tonal-trichord formula"),
                    ("ChordsThirds", "Triads"),
                    ("ChordsSevenths", "Seventh chords"),
                    ("Intervals", "Intervals"),
                ],
                db_index=True,
                default="",
                help_text="Poly lesson category. Empty for mono.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="formula_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Mono formula family: 'Octave', 'Quinta', 'Extended'. Empty for poly.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="interval_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Poly interval family: 'Thirds', 'Fourths', 'Fifths', 'Sixths', 'Sevenths'.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="inversion",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Figured-bass digits for poly chords: 53/63/64 (triads), 7/65/43/2 (sevenths).",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="part",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Poly progressive section: '1', '2', '1-2', '3', '1-3'. Empty for mono.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="texture",
            field=models.CharField(
                choices=[
                    ("mono", "Monophonic (melodic)"),
                    ("poly", "Polyphonic (harmonic)"),
                ],
                db_index=True,
                default="mono",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="variant",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Mono: 'SKALA', 'ABC', 'KROM', '' (plain), ... Poly: 'v<N>_<F|ABC>[+T]' — v1 = guided model (chord walk-up / interval with tonic), v2 = plain tones, v3 = letter names.",
                max_length=255,
            ),
        ),
    ]
