# Generated by Django 4.2.30 on 2026-09-20 16:14

from django.db import migrations, models


def straighten_lines(apps, schema_editor):
    """Every lesson imported before the field existed keeps the layout it
    already had, which is bars at their natural width rather than stretched."""
    apps.get_model("relative", "Lesson").objects.update(auto_align=False)


class Migration(migrations.Migration):

    dependencies = [
        ("relative", "0010_lesson_separator_space"),
    ]

    operations = [
        migrations.RunPython(straighten_lines, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lesson",
            name="auto_align",
            field=models.BooleanField(
                default=False,
                help_text="Stretch each line to the full width. Off leaves bars at their natural width.",
            ),
        ),
    ]
