# Generated by Django 5.1.15 on 2026-08-30 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        default="student",
                        help_text="Students are tracked; teachers author exercises.",
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Shown instead of the username when set.",
                        max_length=80,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_id",
                    models.PositiveSmallIntegerField(help_text="Chapter number, 1-10."),
                ),
                (
                    "chapter_key",
                    models.CharField(
                        help_text="Chapter mode key, e.g. sing_repeat.", max_length=32
                    ),
                ),
                ("chapter_title", models.CharField(blank=True, max_length=120)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="Average score for the run, 0-100."
                    ),
                ),
                (
                    "rounds",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Rounds completed in the run."
                    ),
                ),
                ("system", models.CharField(blank=True, max_length=16)),
                ("texture", models.CharField(blank=True, max_length=16)),
                ("key_name", models.CharField(blank=True, max_length=64)),
                ("formula", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_pr_user_id_a06907_idx",
                    )
                ],
            },
        ),
    ]
