# Generated by Django 5.1.15 on 2026-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                help_text="How much pitch error the exercises allow before scoring it down.",
                max_length=16,
            ),
        ),
    ]
