# Generated by Django 4.2.30 on 2026-09-20 16:33

from django.db import migrations, models


def promote_existing_teachers(apps, schema_editor):
    """Everyone who was a teacher becomes an administrator.

    "Teacher" used to mean the whole editor, curriculum included, and the
    people holding it have been using it that way.  Splitting the role is not
    a reason to take the curriculum away from them overnight: they keep what
    they had, and the narrower role is what *new* teachers are given.
    """
    apps.get_model("accounts", "Profile").objects.filter(role="teacher").update(role="admin")


def demote_admins(apps, schema_editor):
    apps.get_model("accounts", "Profile").objects.filter(role="admin").update(role="teacher")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_difficulty"),
    ]

    operations = [
        migrations.RunPython(promote_existing_teachers, demote_admins),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Administrator"),
                ],
                default="student",
                help_text="Students are tracked; teachers write dictations; administrators own the curriculum.",
                max_length=16,
            ),
        ),
    ]
