# Generated by Django 5.1.15 on 2026-07-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChromaticBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Ap_12'.", max_length=64, unique=True
                    ),
                ),
                ("clef", models.CharField(default="Violin", max_length=32)),
                (
                    "default_rhythm",
                    models.CharField(default="FreeStyle", max_length=32),
                ),
                ("draw_only_note_heads", models.BooleanField(default=True)),
                ("tempo", models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Formula", "Formula"),
                            ("FormulaInverse", "Formula inverse"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "span",
                    models.CharField(
                        choices=[
                            ("Quinta", "Quinta (within a fifth)"),
                            ("Octave", "Octave"),
                            ("Extended", "Extended (beyond the octave)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "grades",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Extended-span grade level: '2Grades', '3Grades' or ''.",
                        max_length=16,
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Progressive section: '1'..'4' or cumulative '1-2', '1-3', '1-4'; '' when the span has no parts.",
                        max_length=8,
                    ),
                ),
                (
                    "exercise_number",
                    models.PositiveSmallIntegerField(
                        help_text="The ex-N number from the source filename (1-12)."
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        help_text="e.g. 'listening_model', 'guessing_notes', 'singing_given_model'.",
                        max_length=64,
                    ),
                ),
                ("timed", models.BooleanField(default=False)),
                (
                    "chromatic",
                    models.BooleanField(
                        default=False,
                        help_text="True when the exercise covers the chromatic scale.",
                    ),
                ),
                ("source_file", models.CharField(default="", max_length=512)),
                ("tempo", models.PositiveIntegerField(default=86)),
                ("draw_only_note_heads", models.BooleanField(default=False)),
                (
                    "default_rhythm",
                    models.CharField(default="FreeStyle", max_length=32),
                ),
                ("mid_bar_time", models.FloatField(default=0.1)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="absolute.chromaticbase",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "span", "grades", "part", "exercise_number"),
                "unique_together": {
                    ("category", "span", "grades", "part", "exercise_number")
                },
            },
        ),
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bar_index", models.PositiveSmallIntegerField()),
                ("music_clef", models.CharField(default="Violin", max_length=32)),
                ("music_rhythm", models.CharField(default="FreeStyle", max_length=32)),
                ("music_mode_chord", models.CharField(default="", max_length=64)),
                ("is_incomplete_bar", models.BooleanField(default=False)),
                (
                    "incomplete_bar_playback_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="absolute.chromaticbase",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="absolute.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ("bar_index",),
            },
        ),
        migrations.CreateModel(
            name="MusicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_index", models.PositiveSmallIntegerField()),
                ("horizontal_offset_ms", models.IntegerField(default=0)),
                ("duration", models.FloatField(default=0.125)),
                ("attack_decay_time", models.FloatField(blank=True, null=True)),
                ("volume", models.PositiveSmallIntegerField(default=80)),
                (
                    "note_name",
                    models.CharField(
                        help_text="Raw token, e.g. 'c1', 'c1#', 'hb'.", max_length=16
                    ),
                ),
                (
                    "alias_degree",
                    models.CharField(
                        default="",
                        help_text="The label from the source alias (chromatic index in the base).",
                        max_length=16,
                    ),
                ),
                ("is_rest", models.BooleanField(default=False)),
                ("is_enharmonic", models.BooleanField(default=False)),
                (
                    "event_type",
                    models.CharField(default="MusicNoteBundle", max_length=64),
                ),
                ("pitch_class", models.SmallIntegerField(default=-1)),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="absolute.bar",
                    ),
                ),
            ],
            options={
                "ordering": ("event_index",),
            },
        ),
    ]
