# Generated by Django 5.1.15 on 2026-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": (
                    "texture",
                    "category",
                    "span",
                    "grades",
                    "quality",
                    "interval_size",
                    "inversion",
                    "part",
                    "phase",
                    "exercise_number",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bar",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text label from the source (e.g. chord/interval name shown above the bar).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="interval_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Poly interval size: 'Seconds'..'Sevenths', 'Eights' (octaves).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="inversion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Figured-bass digits for poly chords: 53/63/64 (triads), 7/65/43/2 (sevenths).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="phase",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Poly pedagogical phase: 1 = melodic presentation, 2 = harmonic. 0 = n/a (mono).",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quality",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Poly quality: chord quality ('DominantSeventh', ..., 'Major', 'Diminished') or interval quality ('Major', 'Minor', 'Perfect', 'Augmented'; empty for fifths/octaves).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="texture",
            field=models.CharField(
                choices=[
                    ("mono", "Monophonic (melodic)"),
                    ("poly", "Polyphonic (harmonic)"),
                ],
                default="mono",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("Formula", "Formula"),
                    ("FormulaInverse", "Formula inverse"),
                    ("Intervals", "Intervals"),
                    ("ChordsThirds", "Triads"),
                    ("ChordsSevenths", "Seventh chords"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="exercise_type",
            field=models.CharField(
                help_text="e.g. 'listening_model', 'guessing_notes', 'guessing_chord'.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="grades",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mono Extended-span grade level: '2Grades', '3Grades' or ''.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="span",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Quinta", "Quinta (within a fifth)"),
                    ("Octave", "Octave"),
                    ("Extended", "Extended (beyond the octave)"),
                ],
                default="",
                help_text="Mono pitch range. Empty for poly.",
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={
                (
                    "texture",
                    "category",
                    "span",
                    "grades",
                    "quality",
                    "interval_size",
                    "inversion",
                    "part",
                    "phase",
                    "exercise_number",
                )
            },
        ),
    ]
