# Generated by Django 5.1.15 on 2026-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0002_alter_lesson_options_alter_lesson_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("Formula", "Formula"),
                    ("FormulaInverse", "Formula inverse"),
                    ("Intervals", "Intervals"),
                    ("ChordsThirds", "Triads"),
                    ("ChordsSevenths", "Seventh chords"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="exercise_number",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="The ex-N number from the source filename (1-12).",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="exercise_type",
            field=models.CharField(
                db_index=True,
                help_text="e.g. 'listening_model', 'guessing_notes', 'guessing_chord'.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="grades",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Mono Extended-span grade level: '2Grades', '3Grades' or ''.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="interval_size",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Poly interval size: 'Seconds'..'Sevenths', 'Eights' (octaves).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="inversion",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Figured-bass digits for poly chords: 53/63/64 (triads), 7/65/43/2 (sevenths).",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="part",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Progressive section: '1'..'4' or cumulative '1-2', '1-3', '1-4'; '' when the span has no parts.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="phase",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Poly pedagogical phase: 1 = melodic presentation, 2 = harmonic. 0 = n/a (mono).",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="quality",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Poly quality: chord quality ('DominantSeventh', ..., 'Major', 'Diminished') or interval quality ('Major', 'Minor', 'Perfect', 'Augmented'; empty for fifths/octaves).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="span",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Quinta", "Quinta (within a fifth)"),
                    ("Octave", "Octave"),
                    ("Extended", "Extended (beyond the octave)"),
                ],
                db_index=True,
                default="",
                help_text="Mono pitch range. Empty for poly.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="texture",
            field=models.CharField(
                choices=[
                    ("mono", "Monophonic (melodic)"),
                    ("poly", "Polyphonic (harmonic)"),
                ],
                db_index=True,
                default="mono",
                max_length=8,
            ),
        ),
    ]
