# Generated by Django 5.1.15 on 2026-08-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "absolute",
            "0003_alter_lesson_category_alter_lesson_exercise_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="span",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Quinta", "Dominant (within a fifth)"),
                    ("Octave", "Octave"),
                    ("Extended", "Extended (beyond the octave)"),
                ],
                db_index=True,
                default="",
                help_text="Mono pitch range. Empty for poly.",
                max_length=32,
            ),
        ),
    ]
