# Generated by Django 5.1.15 on 2026-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0004_alter_lesson_span"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicevent",
            name="visual_offset_px",
            field=models.SmallIntegerField(default=0),
        ),
    ]
