# Generated by Django 5.1.15 on 2026-09-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0005_musicevent_visual_offset_px"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_draft",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_draft", False)),
                fields=(
                    "texture",
                    "category",
                    "span",
                    "grades",
                    "quality",
                    "interval_size",
                    "inversion",
                    "part",
                    "phase",
                    "exercise_number",
                ),
                name="absolute_lesson_identity",
            ),
        ),
    ]
