# Generated by Django 5.1.15 on 2026-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0006_alter_lesson_unique_together_lesson_is_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicevent",
            name="tuplet_den",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="musicevent",
            name="tuplet_num",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
