# Generated by Django 5.1.15 on 2026-09-01 02:14

from django.db import migrations, models


def shelve_drafts(apps, schema_editor):
    """Carry `is_draft` across to the shelf it became.

    A draft is a lesson on the draft shelf; every other lesson is in the
    curriculum, which is the default.  Written out rather than left to the
    column drop, because a migration that silently loses which exercises were
    unfinished would be discovered by a teacher and not by a test.
    """
    Lesson = apps.get_model("absolute", "Lesson")
    Lesson.objects.filter(is_draft=True).update(shelf="draft")


def unshelve_drafts(apps, schema_editor):
    Lesson = apps.get_model("absolute", "Lesson")
    Lesson.objects.filter(shelf="draft").update(is_draft=True)


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0007_musicevent_tuplet_den_musicevent_tuplet_num"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lesson",
            name="absolute_lesson_identity",
        ),
        migrations.AddField(
            model_name="lesson",
            name="shelf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "In the curriculum"),
                    ("draft", "Draft — not filed yet"),
                    ("dictation", "Dictation"),
                ],
                db_index=True,
                default="",
                max_length=16,
            ),
        ),
        migrations.RunPython(shelve_drafts, unshelve_drafts),
        migrations.RemoveField(
            model_name="lesson",
            name="is_draft",
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shelf", "")),
                fields=(
                    "texture",
                    "category",
                    "span",
                    "grades",
                    "quality",
                    "interval_size",
                    "inversion",
                    "part",
                    "phase",
                    "exercise_number",
                ),
                name="absolute_lesson_identity",
            ),
        ),
    ]
