# Generated by Django 4.2.30 on 2026-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absolute", "0008_remove_lesson_absolute_lesson_identity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="align_to_center",
            field=models.BooleanField(
                default=False,
                help_text="Centre each line rather than starting it at the left margin.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="are_all_notes_same_duration",
            field=models.BooleanField(
                default=False,
                help_text="Draw every note as the same value. What is played is unchanged.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="auto_align",
            field=models.BooleanField(
                default=True,
                help_text="Stretch each line to the full width. Off leaves bars at their natural width.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="bar_number_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("all", "Every bar"),
                    ("row", "First bar of each line"),
                ],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="bars_per_row",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Bars on each line; 0 fits as many as the width allows.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="mid_bar_space",
            field=models.PositiveSmallIntegerField(
                default=22,
                help_text="Whitespace between two bars on the page, in pixels.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="mute_last_played_notes_after_bar_finishes",
            field=models.BooleanField(
                default=False,
                help_text="Cut the last note of a bar at the barline. Off lets it ring into the gap, which is what makes a phrase carry across the bar.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="note_label_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nothing"),
                    ("degree", "Scale degrees"),
                    ("letter", "Note names"),
                    ("letter_octave", "Note names with octave"),
                    ("roman", "Roman numerals"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="separator_cancel_previous_note",
            field=models.BooleanField(
                default=False,
                help_text="Cut the note before a separator rather than letting it ring through it.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="separator_time",
            field=models.FloatField(
                default=0.0, help_text="Silence at a separator, in seconds."
            ),
        ),
        migrations.AddField(
            model_name="musicevent",
            name="notehead",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Normal"),
                    ("cross", "Cross"),
                    ("diamond", "Diamond"),
                    ("triangle", "Triangle"),
                    ("square", "Square"),
                    ("slash", "Slash"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="musicevent",
            name="separator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("apostrophe", "Apostrophe (breath)"),
                    ("thin", "Thin barline"),
                    ("thick", "Thick barline"),
                    ("double", "Double barline"),
                    ("dashed", "Dashed barline"),
                    ("marker", "Marker"),
                ],
                default="",
                help_text="A mark drawn after this note — a breath, a phrase line, a tick.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="draw_only_note_heads",
            field=models.BooleanField(
                default=False,
                help_text="Hide stems, flags and beams — the eye stays on where the note sits.",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="mid_bar_time",
            field=models.FloatField(
                default=0.1, help_text="Silence after each bar, in seconds."
            ),
        ),
    ]
