# Generated by Django 4.2.30 on 2026-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScoreStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mid_bar_space",
                    models.PositiveSmallIntegerField(
                        default=22,
                        help_text="Whitespace between two bars on the page, in pixels.",
                    ),
                ),
                (
                    "bars_per_row",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Bars on each line; 0 fits as many as the width allows.",
                    ),
                ),
                (
                    "align_to_center",
                    models.BooleanField(
                        default=False,
                        help_text="Centre each line rather than starting it at the left margin.",
                    ),
                ),
                (
                    "auto_align",
                    models.BooleanField(
                        default=True,
                        help_text="Stretch each line to the full width. Off leaves bars at their natural width.",
                    ),
                ),
                (
                    "draw_only_note_heads",
                    models.BooleanField(
                        default=False,
                        help_text="Hide stems, flags and beams — the eye stays on where the note sits.",
                    ),
                ),
                (
                    "are_all_notes_same_duration",
                    models.BooleanField(
                        default=False,
                        help_text="Draw every note as the same value. What is played is unchanged.",
                    ),
                ),
                (
                    "note_label_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Nothing"),
                            ("degree", "Scale degrees"),
                            ("letter", "Note names"),
                            ("letter_octave", "Note names with octave"),
                            ("roman", "Roman numerals"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "bar_number_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("all", "Every bar"),
                            ("row", "First bar of each line"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "mid_bar_time",
                    models.FloatField(
                        default=0.1, help_text="Silence after each bar, in seconds."
                    ),
                ),
                (
                    "mute_last_played_notes_after_bar_finishes",
                    models.BooleanField(
                        default=False,
                        help_text="Cut the last note of a bar at the barline. Off lets it ring into the gap, which is what makes a phrase carry across the bar.",
                    ),
                ),
                (
                    "separator_time",
                    models.FloatField(
                        default=0.0, help_text="Silence at a separator, in seconds."
                    ),
                ),
                (
                    "separator_cancel_previous_note",
                    models.BooleanField(
                        default=False,
                        help_text="Cut the note before a separator rather than letting it ring through it.",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The house style: what a new exercise starts from.",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "name"),
            },
        ),
    ]
