# Generated by Django 4.2.30 on 2026-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rea_api", "0002_house_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorestyle",
            name="separator_space",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Whitespace around a separator on the page, in pixels.",
            ),
        ),
    ]
