# Generated by Django 4.2.30 on 2026-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rea_api", "0003_scorestyle_separator_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorestyle",
            name="auto_align",
            field=models.BooleanField(
                default=False,
                help_text="Stretch each line to the full width. Off leaves bars at their natural width.",
            ),
        ),
    ]
